version: '3'

services:
  transactionserver:
    image: stocktradingapp/transaction_server

    build:
      context: ./UserActions
      dockerfile: Dockerfile_Engine
    # ports:
    #   - 5000:5000
    restart: on-failure

  # trigger:
  #   image: stocktradingapp/triggers
  #   container_name: triggers
  #   build:
  #     context: ./UserActions
  #     dockerfile: Dockerfile_Triggers
  #   ports:
  #     - 6000:6000
  #   restart: on-failure

  webserver:
    image: stocktradingapp/webserver
    build:
      context: ./WebServer
    ports:
      - "2000-2003:4000"
    depends_on:
      - transactionserver
    restart: on-failure

  reactclient:
    image: stocktradingapp/reactclient
    container_name: react_client
    build:
      context: ./ReactClient
    depends_on:
      - webserver
    ports:
      - 3000:3000
    restart: on-failure

  lbtransac:
    image: lb_t
    container_name: lb_t
    build:
      context: ./LbTransacServer
    depends_on:
      - transactionserver
      - reactclient
    ports: 
      - 5000:5000

  lbweb:
    image: lb_w
    container_name: lb_w
    build:
      context: ./LbWebServer
    depends_on:
      # - transactionserver
      - webserver
      - reactclient
    ports: 
      - 4000:4000

  # k6:
  #   image: grafana/k6
  #   ports: 
  #     - 6565:6565
  #   volumes:
  #     - ./scripts:/scripts
